# Generated by Django 2.0.2 on 2018-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='无标题', max_length=100)),
                ('content', models.TextField(default='...', max_length=5000)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
